config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :foods

  resources :users do
    resources :orders do
      get 'add_food', to: 'foods#index'
      post 'add_food/:id', to: 'foods#add_food'
      get "/foods/:id", to: 'foods#show'
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'
  #post 'add_food', to: 'orders#add_food'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :balance, presence: true
  validate :first_name_capitalized
  validate :last_name_capitalized
  validate :valid_email
  validate :non_zero_balance

  has_many :users_orders, dependent: :destroy
  has_many :orders, through: :users_orders

  include BCrypt

  def full_name
    first_name + ' ' + last_name
  end

  def password
    @password ||= Password.new(password_hash) unless password_hash.nil?
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  private

  def first_name_capitalized
    errors.add(:first_name, 'should be capialized') if !first_name.nil? && first_name[0] != first_name[0].upcase
  end

  def last_name_capitalized
    errors.add(:last_name, 'should be capitalized') if !last_name.nil? && last_name[0] != last_name[0].upcase
  end

  def valid_email
    errors.add(:email, 'should be valid') if !email.nil? && (!email.include?('@') || !email.include?('.'))
  end

  def non_zero_balance
    errors.add(:balance, 'should be valid') if balance < 0
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def email
    @user.email
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    reset_session if current_user.email != 'sohamd@seas.upenn.edu'
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Account was succesfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :balance)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email, class: 'form-control' %>
  </div>

  <% if !logged_in? %>
  <div class="field form-group">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, class: 'form-control' %>
  </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :balance %>
    <%= form.number_field :balance, id: :user_balance, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark bg-dark">Name</th>
      <th class="table-dark bg-dark">Last Name</th>
      <th class="table-dark bg-dark">Email</th>
      <th class="table-dark bg-dark" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <% if logged_in? && current_user.email == "sohamd@seas.upenn.edu" && current_user != user %>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-12">
    <h2>
      <%= @user.full_name %>'s Profile
      <div class="float-right">
        <% if logged_in? %>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_user_path(current_user), class: 'btn btn-dark' %>
            <%= link_to 'Delete Account', current_user, method: :delete, class: 'btn btn-danger' %>
          <% end %>
        <% end %>
      </div>
    </h2>
  </div>
</div>
<p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @user.balance %>
</p>

<%= link_to 'Back', users_path %>