config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :foods

  resources :users do
    resources :orders do
      get 'add_food', to: 'foods#index'
      post 'add_food/:id', to: 'foods#add_food'
      get "/foods/:id", to: 'foods#show'
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'
  #post 'add_food', to: 'orders#add_food'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :orders_foods, dependent: :destroy
  has_many :foods, through: :orders_foods
  has_many :users_orders, dependent: :destroy
  has_many :users, through: :users_order

  def add_food(food)
    OrdersFood.new(order: self, food: food).save
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :add_food, :destroy]
  before_action :set_user, only: [:index, :new, :create, :add_food, :edit, :update, :destroy, :create_helper]
  before_action :set_food, only: [:add_food]

  # GET /orders
  # GET /orders.json
  def index
    @orders = @user.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    create_helper
    respond_to do |format|
      if @order.save
        format.html { redirect_to "/users/#{@user.id}/orders/#{@order.id}", notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to "/users/#{@user.id}/orders/#{@order.id}", notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to "/users/#{@user.id}/orders", notice: 'Order was successfully Cancelled.' }
      format.json { head :no_content }
    end
  end

  def add_food
    @order.add_food(@food)
    redirect_back(fallback_location: @user_order)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_food
    @food = Food.find(params[:food_id])
  end

  def create_helper
    @order = Order.new(order_params)
    @user.orders << @order
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:name, :date)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: [user, order], local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p>Start by naming your order and selecting your delivery date and time. </p>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :order_name %>
  </div>

  <div class="field">
    <%= form.label :'delivery Date' %>
    <%= form.datetime_select :date, id: :order_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', user: @user, order: @order %>

<%= link_to 'Show', @user_order %> |
<%= link_to 'Back', @user_orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark bg-dark">Name</th>
      <th class="table-dark bg-dark">Delivery Date</th>
      <th class="table-dark bg-dark" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.date %></td>
        <td><%= link_to 'View', "/users/#{@user.id}/orders/#{order.id}" %></td>
        <td><%= link_to 'Edit', "/users/#{@user.id}/orders/#{order.id}/edit" %></td>
        <td><%= link_to 'Cancel Order', "/users/#{@user.id}/orders/#{order.id}", method: :delete, data: { confirm: 'Are you sure? Cancellation charges may apply.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_user_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', user: @user, order: @order %>

<%= link_to 'Back', user_orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Delivery Date:</strong>
  <%= @order.date %>
</p>

<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark bg-dark">Foods</th>
      <th class="table-dark bg-dark">Cost</th>
    </tr>
  </thead>

  <% total_cost= 0 %>
  <tbody>
    <% @order.foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.cost %></td>
        <% total_cost = total_cost + food.cost %>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <strong>Total Cost:</strong>
  <%= total_cost %>
</p>

<p>Select add foods to customize your order with some of our delicious menu items! </p>

<% if logged_in? %>
    <%= link_to 'Add Foods', "#{@order.id}/add_food" %>
<% end %> |
<%= link_to 'Back', user_orders_path %>