config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :foods

  resources :users do
    resources :orders do
      get 'add_food', to: 'foods#index'
      post 'add_food/:id', to: 'foods#add_food'
      get "/foods/:id", to: 'foods#show'
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'
  #post 'add_food', to: 'orders#add_food'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :orders_foods, dependent: :destroy
  has_many :orders, through: :orders_foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy, :add_food]
  before_action :set_order, only: [:add_food, :order_index]
  before_action :set_user, only: [:add_food]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_food
    if current_user.balance >= @food.cost
      current_order.add_food(@food)
      new_balance = current_user.balance - @food.cost
      current_user.update_column(:balance, new_balance)
      redirect_to "/users/#{current_user.id}/orders/#{current_order.id}/add_food", notice: 'The food has been added to your order.'
    else
      redirect_to "/users/#{current_user.id}/orders/#{current_order.id}/add_food", notice: 'We could not add the food, as your balance is too low.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_order
    @order = Order.find(params[:order_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def food_params
    params.require(:food).permit(:name, :order_id, :cost, :description)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :food_name %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.number_field :cost, id: :food_cost %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 3, class: 'form-control', id: :status_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark bg-dark">Name</th>
      <th class="table-dark bg-dark">Cost</th>
      <th class="table-dark bg-dark" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.cost %></td>
        <% if ordering? %>
        <td><%= link_to 'Details/Order', "/users/#{current_user.id}/orders/#{current_order.id}/foods/#{food.id}" %></td>
        <% else %>
        <td><%= link_to 'Details', food %></td>
         <% end %>
        <% if logged_in? && current_user.email == "sohamd@seas.upenn.edu"%>
          <td><%= link_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% if ordering? %>
          <td><%= link_to 'Add Food', "/users/#{current_user.id}/orders/#{current_order.id}/add_food/#{food.id}", method: :post %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if !ordering? %>
<p>Create a new order to get any of these delicious menu items!</p>
<br>
<% end %>

<% if ordering? %>
<p>Select the Foods You Would Like to Add to Your Order.</p>
<br>
<% end %>

<%if logged_in? && current_user.email == "sohamd@seas.upenn.edu" %>
  <%= link_to 'New Food', new_food_path %>
<% end %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @food.cost %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<% if logged_in? && ordering?%>
    <%= link_to 'Add to Order', "/users/#{current_user.id}/orders/#{current_order.id}/add_food/#{@food.id}", method: :post %> |
    <%#/users/:user_id/orders/:id/add_food(.:format)%>
<% end %>

<% if logged_in? && current_user.email == 'sohamd@seas.upenn.edu' %>
    <%= link_to 'Edit', edit_food_path(@food) %> |
<% end %>

<% if logged_in? && ordering? %>
<%= link_to 'Back', "/users/#{current_user.id}/orders/#{current_order.id}/add_food" %>
<% else %>
<%= link_to 'Back', foods_path %>
<%end %>