config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :foods

  resources :users do
    resources :orders do
      get 'add_food', to: 'foods#index'
      post 'add_food/:id', to: 'foods#add_food'
      get "/foods/:id", to: 'foods#show'
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'
  #post 'add_food', to: 'orders#add_food'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
  <div class="container">
    <%= link_to 'UberEatsLite', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
        <li class ="nav-item"><%= link_to 'Foods', foods_path, class: 'nav-link' %></li>

        <%# Only display the current user's name, friend requests and log out links if a user is logged in %>
        <%if logged_in? %>
          <li class="nav-item"><%= link_to current_user.full_name, current_user, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'My Orders', "/users/#{current_user.id}/orders", class: 'nav-link'%>
          <li class="nav-item"><%= link_to 'Log out', '/logout', method: :delete, class: 'nav-link' %></li>
        <% end %>
        <%# Only display the sign up and log in links if no user is logged in %>
        <%if !logged_in? %>
          <li class="nav-item"><%= link_to 'Sign up', new_user_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Log in', '/login', class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CIS196FinalProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>